DX-2429 Add README
Bandwidth-Samples/voice-gather-csharp pull request #3
Opened 2022-02-17 16:44 UTC by ckoegel

2022-02-17 22:11 UTC, hamermike requested changes

2022-02-17 22:11 UTC, hamermike commented on README.md
> +This can be accomplisehd by opening both projects in Microsoft Visual Studio and run using the button in the toolbar.
```suggestion
This can be accomplished by opening both projects in Microsoft Visual Studio and run using the button in the toolbar.
```

2022-02-17 22:11 UTC, hamermike commented on README.md
> +Use the following command/s to run the application:
```suggestion
Use the following commands to run the application:
```

2022-02-17 22:11 UTC, hamermike commented on README.md
> +Below are the callback paths:
`callInitiated` is missing from the list.

2022-02-18 14:18 UTC, ckoegel commented on README.md
> +This can be accomplisehd by opening both projects in Microsoft Visual Studio and run using the button in the toolbar.
```suggestion
This can be accomplished by opening both projects in Microsoft Visual Studio and running them using the button in the toolbar.
```

2022-02-18 14:42 UTC, hamermike approved these changes

2022-02-18 20:37 UTC, merged